In [2]:
import torch

In [9]:
# Learning pytorch cdist
a = torch.tensor([[3, 4], [-0.3108, -2.4423], [-0.4821,  1.059]])
b = torch.tensor([[3, 4], [-0.6986,  1.3702]])
dists = torch.cdist(a, b, p=2) # p=2 means norm 2, or euclidian distance
print(dists)

# row i of dists is the distances of element i in a
# col j of dists is the distances of element i in a compared to element j of b

tensor([[0.0000, 4.5382],
        [7.2432, 3.8322],
        [4.5579, 0.3791]])


# Prototypical Network

## Sizes in original version:

support_features: [25, 512]

query_features: [25, 512]

prototypes: [5, 512]

dists: [50, 5]

In [31]:
# Prototypical Network
support_features = torch.rand((3,10))
query_features = torch.rand((5,10))

print("support:", support_features)

n_way = 3

support_labels = torch.tensor([0,1,2])

# Prototype i is the mean of all instances of features corresponding to labels == i
prototypes = torch.cat([support_features[torch.nonzero(support_labels==i)].mean(0) 
                        for i in range(n_way)])

print("prototypes:",prototypes)

dists = torch.cdist(query_features, prototypes)
# print(dists)

scores = -dists
# print(scores)

# scores are negative of dists because the largest (least negative)
# score value is the answer, and the smallest distance is the answer

support: tensor([[0.7511, 0.7107, 0.5242, 0.4270, 0.9622, 0.1226, 0.5837, 0.5515, 0.6753,
         0.2185],
        [0.5593, 0.3586, 0.8593, 0.5987, 0.7437, 0.3188, 0.4466, 0.5877, 0.4988,
         0.9259],
        [0.1332, 0.8960, 0.2055, 0.8800, 0.7347, 0.6509, 0.8275, 0.7082, 0.2440,
         0.2309]])
prototypes: tensor([[0.7511, 0.7107, 0.5242, 0.4270, 0.9622, 0.1226, 0.5837, 0.5515, 0.6753,
         0.2185],
        [0.5593, 0.3586, 0.8593, 0.5987, 0.7437, 0.3188, 0.4466, 0.5877, 0.4988,
         0.9259],
        [0.1332, 0.8960, 0.2055, 0.8800, 0.7347, 0.6509, 0.8275, 0.7082, 0.2440,
         0.2309]])
tensor([[1.0895, 1.0045, 1.0592],
        [1.0871, 0.8147, 1.7394],
        [1.3743, 1.2679, 1.2579],
        [1.1231, 1.0116, 1.3322],
        [1.2640, 1.1765, 1.3550]])
tensor([[-1.0895, -1.0045, -1.0592],
        [-1.0871, -0.8147, -1.7394],
        [-1.3743, -1.2679, -1.2579],
        [-1.1231, -1.0116, -1.3322],
        [-1.2640, -1.1765, -1.3550]])
